# Generated by Django 5.2.1 on 2025-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=122)),
                ('email', models.CharField(verbose_name=122)),
                ('phone', models.CharField(verbose_name=122)),
                ('drc', models.CharField(verbose_name=122)),
            ],
        ),
    ]
